replace set-output with GITHUB_OUTPUT
equisoft-actions/kotlin-workflows pull request #13
Opened 2022-12-31 04:37 UTC by meriouma

2023-01-03 15:45 UTC, Chris-V requested changes

2023-01-03 15:45 UTC, Chris-V commented on .github/workflows/micronaut-gradle.yml
> +          echo "use-emulation={USE_EMULATION}" >> $GITHUB_OUTPUT
```suggestion
          echo "image-name=${IMAGE_NAME}" >> $GITHUB_OUTPUT
          echo "docker-context=${DOCKER_CONTEXT}" >> $GITHUB_OUTPUT
          echo "dockerfile=${DOCKERFILE}" >> $GITHUB_OUTPUT
          echo "subproject-dir=${SUBPROJECT_DIR}" >> $GITHUB_OUTPUT
          echo "micronaut-gradle-installed=$( [ "$MICRONAUT_GRADLE_INSTALLED" = 0 ] && echo true || echo false )" >> $GITHUB_OUTPUT
          echo "openapi-file=${OPENAPI_FILE}" >> $GITHUB_OUTPUT
          echo "build-image-runner=${BUILD_IMAGE_RUNNER}" >> $GITHUB_OUTPUT
          echo "use-emulation=${USE_EMULATION}" >> $GITHUB_OUTPUT
```

2023-01-03 15:45 UTC, Chris-V commented on .github/workflows/micronaut-gradle.yml
> +          echo "sdk-generators-matrix=sdk_generators_json" >> $GITHUB_OUTPUT
```suggestion
          echo "sdk-generators-matrix=$sdk_generators_json" >> $GITHUB_OUTPUT
```

2023-01-03 15:45 UTC, Chris-V commented on .github/workflows/micronaut-gradle.yml
> +          echo "image-tag={{ needs.setup.outputs.image-name }}:${{ steps.build-and-push.outputs.image-version }}" >> $GITHUB_OUTPUT
```suggestion
          echo "image-tag=${{ needs.setup.outputs.image-name }}:${{ steps.build-and-push.outputs.image-version }}" >> $GITHUB_OUTPUT
```

2023-01-03 15:45 UTC, Chris-V commented on .github/workflows/micronaut-gradle.yml
> +          echo "filename=filename" >> $GITHUB_OUTPUT
```suggestion
          echo "filename=$filename" >> $GITHUB_OUTPUT
```

2023-01-04 00:28 UTC, Chris-V approved these changes

2023-01-04 15:02 UTC, kbeaulieu approved these changes

2023-01-05 21:46 UTC, merged